VERSION=0.11.1
PACKAGE=zcs-lib-vnc-common
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-libs
PRIORITY=optional
DEPENDS=zcs-core-libs,zcs-lib-gson
DESCRIPTION=Common classes library for VNC packages
REDMINE_UPLOAD_PROJECT=zcs-lib-vnc-common
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
FORCE_ZIMBRA_BASE=helix
