VERSION=0.0.4
PACKAGE=zcs-lib-vnc-common
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=Common classes library for VNC packages
DISTPREFIX=$(TOPDIR)/dist
DISTDIR=$(DISTPREFIX)/$(PACKAGE)-$(VERSION)
DISTFILE=$(DISTPREFIX)/$(PACKAGE)-$(VERSION).tar.gz
JAVA?=java
JAR?=jar
JAVAC?=javac
IMAGE_ROOT=$(TOPDIR)/image
INSTALL_DIR=$(IMAGE_ROOT)/zimlets-install/$(PACKAGE)
REDMINE_UPLOAD_PROJECT=zcs-lib-vnc-common
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
