VERSION=0.6.0
PACKAGE=zcs-lib-vnc-common
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-libs
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=Common classes library for VNC packages
REDMINE_UPLOAD_PROJECT=zcs-lib-vnc-common
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
