
TOPDIR=../../
JAR_FILE_NAME=zcs-lib-vnc-common.jar

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_EXTENSION=y
INSTALL_LIB=y
INSTALL_ZIMLET=y

ZCS_LIB_JARS=\
	servlet-api.jar			\
	zimbrastore.jar			\
	zimbracommon.jar		\
	json.jar			\
	zcs-lib-gson.jar		\
	commons-httpclient.jar		\
	commons-codec.jar

include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-java-lib.mk
