
TOPDIR=../../
JAR_FILE_NAME=zcs-lib-vnc-common.jar

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_EXTENSION=y
INSTALL_LIB=y

ZCS_LIB_JARS=\
	servlet-api.jar		\
	zimbrastore.jar		\
	zimbracommon.jar

include $(TOPDIR)/zcs-java-lib.mk
